### PR TITLE
automatic backend choice

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by djarecka** [comment]
In line 92 should be "serial" backend, not OpenMP

Have run on my Mac and skua - in both cases:
Trying with CUDA backend...  KO!
Trying with OpenMP backend...  KO!
Trying with OpenMP backend...  OK!

Shouldn't try CUDA on skua??

**Comment by slayoo** [comment]
Doroto!

It was "permission denied" issue - I've added your account to the "video" group - after logout/login it should work out of the box. 

Typo fixed.

S.

**Comment by slayoo** [comment]
hmmm.... but why "OpenMP" did not work???

**Comment by slayoo** [comment]
for the record: OpenMP did not work because the libcloudphxx installed on skua was compiled with clang

**Pull request merged**
